dist: trusty
sudo: required
language: go

env:
  - SODA_DIALECT="postgres"
  - SODA_DIALECT="mysql_travis"
  - SODA_DIALECT="sqlite"
#  - SODA_DIALECT="mariadb"

install:
  - go get -t -v ./...
  - go build -v -tags sqlite -o tsoda ./soda

before_script:
  - ./tsoda create -e $SODA_DIALECT
  - ./tsoda migrate -e $SODA_DIALECT

script:
  - go test -tags sqlite ./... -v

global_env:
  - MYSQL_USER="travis"
  - MYSQL_PASSWORD=""
  - POSTGRES_PASSWORD=""

services:
  - mysql

addons:
  postgresql: "9.5"
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

matrix:
  include:
    - dist: trusty
      go: 1.8
      env: SODA_DIALECT="postgres"
    - dist: trusty
      go: 1.8
      env: SODA_DIALECT="mysql_travis"
    - dist: trusty
      go: 1.8
      env: SODA_DIALECT="sqlite"
    - dist: trusty
      go: 1.9
      env: SODA_DIALECT="postgres"
    - dist: trusty
      go: 1.9
      env: SODA_DIALECT="mysql_travis"
    - dist: trusty
      go: 1.9
      env: SODA_DIALECT="sqlite"
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="postgres"
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="mysql_travis"
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="sqlite"
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="postgres"
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="mysql_travis"
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="sqlite"
  allow_failures:
    - go: 'tip'
